id = "mel"
name = "MEL (Maya Embedded Language)"
version = "0.1.0"
schema_version = 1
authors = ["Jon Macey"]
description = "Syntax highlighting for Maya Embedded Language"

[[language]]
name = "MEL"
language_id = "mel"
file_extensions = ["mel"]
grammar = "mel"

[grammars.mel]
path = "grammars/mel"
repository = "file:///Volumes/teaching/Code/ZedMel/tree-sitter-mel"
commit = "main"
